### PR TITLE
Add verify flag to address SSL calls

### PR DESCRIPTION
**Pull request by m4dcoder**
Set verify to False to not verify certs. This should be revisited to allow cert verification.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

How comes this only affects us and not other v1.6.0 installations (at least I haven't heard people complain about it yet)?

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1471852137005315

**Comment by Kami** [comment]
It looks like at least one other user in community is affected.

We should cherry pick this into v1.6.1.

**Comment by Kami** [comment]
Here is a simple work-around from shu on Slack to apply this patch until v1.6.1 is out:

> ( cd /opt/stackstorm/mistral/lib/python2.7/site-packages && curl -sSL https://patch-diff.githubusercontent.com/raw/StackStorm/st2mistral/pull/20.diff | patch -p1 )

**Pull request merged**
